name: Run tests

on: [workflow_dispatch, push, pull_request]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    
    - uses: actions/checkout@v3

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Dependencies
      run: make install

    - name: Create Database
      run: |
        make schema_create
        make load_fixtures

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: make phpunit

    - name: Execute tests via PHPStan
      run: make phpstan

    - name: Execute tests via PHP-CS
      run: make phpcs
      